language: go
go:
  - 1.3

before_install:
  - git submodule update --init --recursive

install:
  - export GOPATH=$HOME/gopath/src/github.com/cloudfoundry/hm-workspace
  - mkdir -p $GOPATH/bin
  - go install -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/apcera/nats
  - go get -v github.com/apcera/gnatsd
  - pushd ./src/github.com/coreos/etcd
  - ./build
  - mv ./bin/etcd $GOPATH/bin
  - popd

script:
  - export GOPATH=$HOME/gopath/src/github.com/cloudfoundry/hm-workspace
  - export PATH=$GOPATH/bin:$PATH
  - cd $GOPATH/src/github.com/cloudfoundry/hm9000
  - ginkgo -r -trace --randomizeAllSpecs --failOnPending
